package com.meows.sir.entity;

public enum EventType {
    WEBHOOK_REGISTERED, WEBHOOK_UNREGISTERED,
    //ITEM_CREATED, ITEM_MODIFIED, ITEM_DELETED,
    //ITEM_IMG_URL_ADDED, ITEM_IMG_URL_MODIFIED, ITEM_IMG_URL_DELETED,
    //ITEM_NOTE_ADDED, ITEM_NOTE_MODIFIED, ITEM_NOTE_DELETED,
    LIST_CREATED, LIST_MODIFIED, LIST_DELETED;
}
